#!/usr/bin/env bash
# Regenerates styler/fonts.css and the woff2 files in this directory.
#
# Edit GF_URL below to change families/weights, then run:
#   ./styler/fonts/fetch-fonts.sh
#
# Keeps only the latin and latin-ext subsets. Everything is downloaded from
# Google, but only at build time - the shipped framework makes no external
# requests.

set -euo pipefail

GF_URL='https://fonts.googleapis.com/css2?family=Source+Sans+3:ital,wght@0,400;0,600;1,400;1,600&family=Inter:wght@400;600&family=PT+Serif:ital,wght@0,400;0,700;1,400;1,700&family=Lora:ital,wght@0,400;0,600;1,400;1,600&family=Crimson+Pro:ital,wght@0,400;0,600;1,400;1,600&family=Cormorant+Garamond:ital,wght@0,400;0,600;1,400;1,600&display=swap'

# A desktop Chrome UA is required, or Google serves ttf instead of woff2.
UA='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'

FONTS_DIR="$(cd "$(dirname "$0")" && pwd)"
CSS_OUT="$(dirname "$FONTS_DIR")/fonts.css"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

curl -sL -A "$UA" "$GF_URL" -o "$TMP/gf.css"

python3 - "$TMP/gf.css" "$CSS_OUT" "$TMP/curlrc" <<'PY'
import re, sys

src_path, css_out, curlrc = sys.argv[1:4]
KEEP = {'latin', 'latin-ext'}

blocks = re.findall(r'/\* ([a-z0-9-]+) \*/\n(@font-face \{.*?\n\})', open(src_path).read(), re.S)

css = ["/* Self-hosted webfonts for Styler - no external dependencies. */",
       "/* Generated by fonts/fetch-fonts.sh - edit that script, not this file. */",
       "/* Fonts are licensed under the SIL Open Font License 1.1 - see fonts/OFL.txt */",
       ""]
seen = {}

for subset, block in blocks:
    if subset not in KEEP:
        continue
    fam   = re.search(r"font-family: '([^']+)'", block).group(1)
    style = re.search(r'font-style: (\w+)', block).group(1)
    wght  = re.search(r'font-weight: ([\d ]+)', block).group(1).strip().replace(' ', '-')
    url   = re.search(r'url\((https://[^)]+)\)', block).group(1)

    name = f"{fam.lower().replace(' ', '-')}-{wght}{'-italic' if style == 'italic' else ''}-{subset}.woff2"
    if name in seen:
        sys.exit('name collision: ' + name)
    seen[name] = url

    css += [f'/* {fam} {wght} {style} - {subset} */',
            block.replace(url, f'fonts/{name}'), '']

open(css_out, 'w').write('\n'.join(css))
open(curlrc, 'w').write('\n'.join(f'url = "{u}"\noutput = "{n}"' for n, u in seen.items()))
print(f'{len(seen)} font files')
PY

rm -f "$FONTS_DIR"/*.woff2
(cd "$FONTS_DIR" && curl -sL -A "$UA" -K "$TMP/curlrc")

echo "Wrote $CSS_OUT and $(ls "$FONTS_DIR"/*.woff2 | wc -l | tr -d ' ') woff2 files ($(du -sh "$FONTS_DIR" | cut -f1))"
